#!/usr/bin/env python3
# encoding: utf-8

area_info = {
    "quz": {
        "enabled": True,
        "name": "quzhou",
        "name_zh_CN": "衢州",
        "area_code": "0570",
        "username": "sdnnetconf",
        "password": "qzdx@123",
        "vsw_info": ["183.150.170.3"],
        "dcsw_info": ["220.185.56.11"],
    },
    "hangz": {
        "enabled": False,
        "name": "hangzhou",
        "name_zh_CN": "杭州",
        "area_code": "0571",
        "username": "sdnnetconf",
        "password": "hz2018",
        "vsw_info": ["0.0.0.0"],
        "dcsw_info": ["0.0.0.0", "1.1.1.1", "2.2.2.2"],
    },
    "huz": {
        "enabled": False,
        "name": "huzhou",
        "name_zh_CN": "湖州",
        "area_code": "0572",
        "username": "sdnnetconf",
        "password": "Huzhou@0572",
        "vsw_info": ["0.0.0.0"],
        "dcsw_info": ["0.0.0.0", "1.1.1.1", "2.2.2.2"],
    },
    "jiax": {
        "enabled": False,
        "name": "jiaxing",
        "name_zh_CN": "嘉兴",
        "area_code": "0573",
        "username": "sdnnetconf",
        "password": "sdn2018@jxdx",
        "vsw_info": ["218.73.114.235"],
        "dcsw_info": ["61.130.190.17"],
    },
    "ningb": {
        "enabled": True,
        "name": "ningbo",
        "name_zh_CN": "宁波",
        "area_code": "0574",
        "username": "sdnnetconf",
        "password": "nb@sdn",
        "vsw_info": ["61.175.6.115"],
        "dcsw_info": ["61.153.86.3"],
    },
    "shaox": {
        "enabled": True,
        "name": "shaoxing",
        "name_zh_CN": "绍兴",
        "area_code": "0575",
        "username": "sdnnetconf@sxacs",
        "password": "92tye%9!",
        "vsw_info": [" 61.175.183.231"],
        "dcsw_info": ["61.130.35.53"],
    },
    "taiz": {
        "enabled": True,
        "name": "taizhou",
        "name_zh_CN": "台州",
        "area_code": "0576",
        "username": "sdnnetconf",
        "password": "sdn@tzdx",
        "vsw_info": ["61.175.76.155"],
        "dcsw_info": ["61.175.80.233"],
    },
    "wenz": {
        "enabled": True,
        "name": "wenzhou",
        "name_zh_CN": "温州",
        "area_code": "0577",
        "username": "sdnnetconf",
        "password": "1808-sdnconf@zj",
        "vsw_info": ["220.186.243.231"],
        "dcsw_info": ["61.174.177.76"],
    },
    "lis": {
        "enabled": True,
        "name": "lishui",
        "name_zh_CN": "丽水",
        "area_code": "0578",
        "username": "sdnnetconf",
        "password": "sdn123!@#",
        "vsw_info": ["218.74.114.87"],
        "dcsw_info": ["218.74.120.12","218.74.120.13"],
    },
    "jinh": {
        "enabled": True,
        "name": "jinhua",
        "name_zh_CN": "金华",
        "area_code": "0579",
        "username": "sdnnetconf",
        "password": "jinhua@2018",
        "vsw_info": ["61.174.195.75"],
        "dcsw_info": ["61.130.42.233"],
    },
    "zhous": {
        "enabled": True,
        "name": "zhoushan",
        "name_zh_CN": "舟山",
        "area_code": "0580",
        "username": "sdnnetconf",
        "password": "SDN_conf@2018",
        "vsw_info": ["61.130.240.19"],
        "dcsw_info": ["115.233.240.47"],
    },
    "zhej": {
        "enabled": False,
        "name": "zhejiang",
        "name_zh_CN": "浙江",
        "area_code": "057X",
        "username": "huawei",
        "password": "Qk1z9fka@8jzu",
        "vsw_info": ["0.0.0.0"],
        "dcsw_info": ["0.0.0.0", "1.1.1.1", "2.2.2.2"],
    }
}
